#!/bin/bash
clear
read -p "Press [Enter] key to start installation..."
apt update
echo
echo
apt-get install -y curl git zip unzip software-properties-common dirmngr ca-certificates apt-transport-https
apt update && apt upgrade -y
curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup |  bash -s -- --mariadb-server-version=10.11  # LTS version
#curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup |  bash -s -- --mariadb-server-version=11.4  # Rolling version
apt install -y nginx mariadb-server mariadb-client
mysql -uroot -e "CREATE DATABASE laravel_db; CREATE USER 'webmaster'@'localhost' IDENTIFIED BY 'Lara@2020'; GRANT ALL ON laravel_db.* TO 'webmaster'@'localhost';"
mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'oum202020'; FLUSH PRIVILEGES;"
add-apt-repository ppa:ondrej/php
apt update && apt upgrade -y
#apt install -y php8.3-fpm php8.3-cli php8.3-curl php8.3-gd php8.3-mbstring php8.3-mysql php8.3-xml php8.3-zip php8.3-sqlite3
apt install -y php8.3-common php8.3-fpm php8.3-zip php8.3-bz2 php8.3-mysql php8.3-xml php8.3-xmlrpc php8.3-curl php8.3-gd php8.3-imagick php8.3-cli php8.3-dev php8.3-imap php8.3-mbstring php8.3-opcache php8.3-soap php8.3-redis php8.3-intl php8.3-sqlite3
echo
echo
cp -Rpv composer.phar /usr/local/bin/composer
chmod +x /usr/local/bin/composer
cd /var/www/html
echo
echo
composer create-project --prefer-dist laravel/laravel test
chown -R :www-data /var/www/html/test/storage/
chown -R :www-data /var/www/html/test/bootstrap/cache/
chmod -R 0777 /var/www/html/test/storage/
echo
echo
mv /etc/php/8.3/fpm/php.ini /etc/php/8.3/fpm/php.ini-bak
mv /var/www/html/test/public/favicon.ico  /var/www/html/test/public/favicon.ico-bak
mkdir -p /etc/ssl/pki
cp -Rpv /home/g33j3t/test.crt /etc/ssl/pki/
cp -Rpv /home/g33j3t/test.key /etc/ssl/pki/
cp -Rpv /home/g33j3t/test.conf /etc/nginx/sites-available/
cp -Rpv /home/g33j3t/php.ini  /etc/php/8.3/fpm/
cp -Rpv /home/g33j3t/favicon-oum.ico  /var/www/html/test/public/favicon.ico
cp -Rpv /home/g33j3t/env-test   /var/www/html/test/.env
unlink /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/test.conf /etc/nginx/sites-enabled/
bash -c "echo -e '<?php\nphpinfo();\n?>' > /var/www/html/test/public/phpinfo.php"
systemctl restart nginx
systemctl restart php8.3-fpm
php /var/www/html/test/artisan migrate
echo
echo
echo "Run installation in web using  http://$(hostname -I | awk '{print $1}')"
echo
echo
echo "Laravel version"
php /var/www/html/test/artisan --version
echo
echo
echo "Nginx version"
nginx -v
echo
echo
echo "Database Server version"
mariadb --version
echo
echo
echo
